### ISSUE TITLE
ImportError: No module named PyPDF2.generic

### ISSUE THREAD

**Issue by joaofrgomes** [cycomanic/Menextract2pdf#21]
Hi guys!
I am trying to migrate my Mendeley Desktop library from v. 1.8 to the latest version of Zotero, on macOS Catalina 10.15.4, and I get the following output on Terminal:
`Traceback (most recent call last):
	File "src/menextract2pdf.py", line 14, in <module>
		import pdfannotation
	File "/Users/johnny/Downloads/Menextract2pdf-master/src/pdfannotation.py", line 10, in <module>
	from PyPDF2.generic import *
ImportError: No module named PyPDF2.generic`
~~I have no idea what I'm doing wrong, and will try doing this in a Windows VM shortly if I don't get feedback soon. In any case, I'll let you know how that went.~~

**Comment by joaofrgomes** [comment]
Hi again guys, sorry for the inconvenience of posing stupid questions before doing due diligence and R-ingTFM. I'm still a bit new to homebrew and Python, and I basically searched around for some tutorials and realized I was missing quite a few modules.
By the way, I updated Python to v. 3.8.2 and then needed dateutil besides the two dependencies mentioned on your documentation. It was a bit of hard work for me, but then it was finally smooth sailing and your script chugged through 13 PDFs in total which had notes.
Yeah, those weren't that many (for context, my library has hundreds of PDFs and I'm about to enter a PhD), but it still saved me a lot of time, and I also realized that I probably stopped taking notes in Mendeley altogether because, deep down, I knew this day would come and was afraid of getting too locked in. Thanks guys! :D
